---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ace.
--- DateTime: 2022/8/19 23:41
---

local class = require 'oop.class'

local static = function() end
local public = function() end
local protected = function() end
local private = function() end
local map

local str

class "walkable" {
    name = { string, static "trait.walkable", not_null },
    suitable = { fn },
    behaviors = { map },
}

